# Makefile

# Define o comando Python a ser usado
PYTHON = python3

# Define o script principal
SCRIPT = questao1.py

# A cláusula 'run' que executa o script Python
run:
	$(PYTHON) $(SCRIPT)

# Um comando para limpar arquivos temporários ou de cache, se necessário
clean:
	rm -rf __pycache__
